"""NOAA passive-acoustic cetacean detections (site-series contract) → public/data/cetaceans.geojson.

Source: the NOAA NEFSC Passive Acoustic Cetacean Map (PACM, https://passiveacoustics.fisheries.noaa.gov/pacm/).
The app has no query API; its Vite bundle loads static files from `/pacm/data/` (read from
`assets/index-Bn0c_FNd.js`, 2026-09-12): per species theme `<theme>/detections.csv` (one row per
deployment × day with `presence` y / n / m(possibly) / na, and for mobile platforms a JSON
`locations` column) and `<theme>/deployments.json` (site, organisation, lat/lon, platform).
Global `organizations.json` maps organisation codes to names. The server gzips on request
(~0.9 MB per theme instead of ~30 MB), and the files are regenerated by NOAA (last-modified
2026-09-02 while the newest detection day was 2026-05-15) — so the public record lags by months
and the client states `data_end` in its legend instead of pretending the layer is live.

One Point per recording station (stationary: `site_id`; mobile glider/buoy: the deployment,
positioned at the mean of its in-window day positions) with `weeks` bins of detection days per
species theme. Counts are DAYS WITH A DETECTION, not calls — one day with one right-whale
upcall and one day with hundreds both count 1. Monitored days (`e`) come along so "no
detection" is distinguishable from "no recorder". Contributor e-mails (`data_poc`) are never
written out; organisations are credited by name.

Licence (NOAA Fisheries Copyright Policy, read 2026-09-12): "Information created by the U.S.
government and presented on U.S. government websites is not subject to copyright in the United
States … we also request that NOAA Fisheries be given appropriate acknowledgement ('Courtesy:
National Oceanic and Atmospheric Administration')". PACM's own citations dialog asks users to
"include the PACM citation … and the list of data contributor citations"; both are emitted.
"""

from __future__ import annotations
import argparse
import collections
import csv
import datetime as dt
import gzip
import io
import json
import logging
import time
import urllib.error
import urllib.request
from pathlib import Path
from .atomic import write_atomic

log = logging.getLogger("cetaceans")
BASE = "https://passiveacoustics.fisheries.noaa.gov/pacm/data"
APP_URL = "https://passiveacoustics.fisheries.noaa.gov/pacm/"
PACM_VERSION = (
    "1.3.8"  # the app's citation string in assets/index-Bn0c_FNd.js, 2026-09-12
)
UA = {"User-Agent": "wildeye (github.com/musharna/wildeye)", "Accept-Encoding": "gzip"}
LICENCE = (
    "Public Domain U.S. Government (NOAA Fisheries Copyright Policy); acknowledge NOAA"
)
# PACM theme id → chip label (theme ids from the bundle's theme list `oU`, 2026-09-12)
THEMES = {
    "narw": "right whale",
    "fin": "fin whale",
    "humpback": "humpback whale",
    "sei": "sei whale",
    "blue": "blue whale",
    "sperm": "sperm whale",
    "dolphin": "dolphins",
}
DET_COLS = (
    "id",
    "analysis_id",
    "deployment_id",
    "species",
    "date",
    "presence",
    "locations",
)
PRESENT = ("y", "n", "m")  # "na" = no analysis that day
WEEK_D = 7
RETRIES = 4
SLEEP = 2.0  # unfamiliar host: ≥2 s between requests


def _get_bytes(
    url: str, timeout: int = 300, retries: int = RETRIES, sleep=time.sleep
) -> bytes:
    req = urllib.request.Request(url, headers=UA)
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                raw = r.read()
                if (r.headers.get("Content-Encoding") or "").lower() == "gzip":
                    raw = gzip.decompress(raw)
                return raw
        except urllib.error.HTTPError as e:
            if e.code < 500 or attempt == retries - 1:
                raise
            log.warning(
                "HTTP %d from %s, retry %d/%d", e.code, url, attempt + 1, retries - 1
            )
            sleep(30 * 2**attempt)
    raise AssertionError("unreachable")


def parse_detections(text: str, since: str) -> list[dict]:
    """Rows of detections.csv dated ≥ `since` (ISO date) with an analysed presence (y/n/m).
    The CSV is not date-ordered (the newest real-time rows come first, then old archives), so
    the whole file is scanned; only the in-window rows are kept."""
    rd = csv.DictReader(io.StringIO(text))
    missing = [c for c in DET_COLS if c not in (rd.fieldnames or [])]
    if missing:
        raise ValueError(f"detections.csv lacks columns {missing}: got {rd.fieldnames}")
    out = []
    for r in rd:
        if r["date"] >= since and r["presence"] in PRESENT:
            out.append(r)
    return out


def fetch_theme(
    theme: str, since: str, fetch=_get_bytes, sleep=time.sleep
) -> tuple[list[dict], dict[str, dict]]:
    """(in-window detection rows, deployments by id) for one PACM theme."""
    dets = parse_detections(
        fetch(f"{BASE}/{theme}/detections.csv").decode("utf-8"), since
    )
    sleep(SLEEP)
    deps = {d["id"]: d for d in json.loads(fetch(f"{BASE}/{theme}/deployments.json"))}
    sleep(SLEEP)
    return dets, deps


def fetch_organizations(fetch=_get_bytes) -> dict[str, str]:
    return {
        o["code"]: o["name"] for o in json.loads(fetch(f"{BASE}/organizations.json"))
    }


def week_ends(data_end: dt.date, weeks: int) -> list[dt.date]:
    """`weeks` 7-day bins ending on `data_end`, newest first (bin k covers (end-7k-6 … end-7k])."""
    return [data_end - dt.timedelta(days=WEEK_D * k) for k in range(weeks)]


def _week_index(day: dt.date, data_end: dt.date) -> int:
    return (data_end - day).days // WEEK_D


def _day_position(row: dict, dep: dict) -> tuple[float, float] | None:
    """(lat, lon) for one detection day: mean of the mobile `locations`, else the deployment's."""
    locs = row.get("locations")
    if locs and locs != "null":
        pts = [
            (float(p["latitude"]), float(p["longitude"]))
            for p in json.loads(locs)
            if p.get("latitude") is not None and p.get("longitude") is not None
        ]
        if pts:
            return sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts)
    if dep.get("latitude") is None or dep.get("longitude") is None:
        return None
    return float(dep["latitude"]), float(dep["longitude"])


def _monitored(date: str, dep: dict) -> bool:
    """A detection day must lie inside its deployment's monitoring window. PACM's sperm-whale
    theme carries 2018 PIFSC drifting-buoy deployments whose rows are dated 2026 (912 rows on
    2026-09-12, every one outside the window) — analysis dates leaking into `date`. Deployments
    without both monitoring dates cannot be checked and are kept."""
    s = (dep.get("monitoring_start_datetime") or "")[:10]
    e = (dep.get("monitoring_end_datetime") or "")[:10]
    return not (s and e) or s <= date <= e


def aggregate(
    themes: dict[str, tuple[list[dict], dict[str, dict]]],
    weeks: int,
    data_end: dt.date | None = None,
) -> tuple[list[dict], dict]:
    """Station features with weekly per-theme detection days over the last `weeks` bins.

    `themes` = {theme: (rows, deployments)}; per-station keys are the THEMES labels. Station
    key: stationary → (org, site_id); mobile → (org, deployment_id). `data_end` defaults to the newest analysed day across
    themes. Returns (features, counts)."""
    counts = {
        "rows": sum(len(r) for r, _ in themes.values()),
        "no_deployment": 0,
        "outside_monitoring": 0,
        "no_position": 0,
        "outside_window": 0,
        "detection_days": 0,
    }
    if data_end is None:
        days = [r["date"] for rows, _ in themes.values() for r in rows]
        if not days:
            return [], counts | {"stations": 0, "organizations": 0, "data_end": None}
        data_end = dt.date.fromisoformat(max(days))
    stations: dict[tuple, dict] = {}
    for theme, (rows, deps) in themes.items():
        for r in rows:
            dep = deps.get(r["deployment_id"])
            if dep is None:
                counts["no_deployment"] += 1
                continue
            if not _monitored(r["date"], dep):
                counts["outside_monitoring"] += 1
                continue
            day = dt.date.fromisoformat(r["date"])
            k = _week_index(day, data_end)
            if k < 0 or k >= weeks:
                counts["outside_window"] += 1
                continue
            pos = _day_position(r, dep)
            if pos is None:
                counts["no_position"] += 1
                continue
            mobile = dep.get("deployment_type") == "MOBILE"
            org = dep.get("deployment_organization_code") or ""
            key = (org, dep["id"] if mobile else (dep.get("site_id") or dep["id"]))
            st = stations.setdefault(
                key,
                {
                    "name": (dep.get("deployment_code") if mobile else dep.get("site"))
                    or key[1],
                    "project": dep.get("project") or "",
                    "platform": dep.get("platform_type") or "",
                    "mobile": mobile,
                    "qc": set(),
                    "codes": collections.defaultdict(set),
                    "pos": [],
                    "det": [collections.Counter() for _ in range(weeks)],
                    "maybe": [collections.Counter() for _ in range(weeks)],
                    "effort": [set() for _ in range(weeks)],
                },
            )
            if dep.get("qc_data"):
                st["qc"].add(dep["qc_data"])
            st["pos"].append(pos)
            st["effort"][k].add(r["date"])
            label = THEMES.get(theme, theme)
            if r["presence"] == "y":
                st["det"][k][label] += 1
                st["codes"][label].add(r["species"])
                counts["detection_days"] += 1
            elif r["presence"] == "m":
                st["maybe"][k][label] += 1
    features = []
    ends = week_ends(data_end, weeks)
    for (org, sid), st in sorted(stations.items()):
        lat = round(sum(p[0] for p in st["pos"]) / len(st["pos"]), 4)
        lon = round(sum(p[1] for p in st["pos"]) / len(st["pos"]), 4)
        total, maybe = collections.Counter(), collections.Counter()
        for c in st["det"]:
            total.update(c)
        for c in st["maybe"]:
            maybe.update(c)
        features.append(
            {
                "type": "Feature",
                "geometry": {"type": "Point", "coordinates": [lon, lat]},
                "properties": {
                    "station": st["name"],
                    "org": org,
                    "project": st["project"],
                    "platform": st["platform"],
                    "mobile": st["mobile"],
                    "qc": sorted(st["qc"]),
                    "species": dict(sorted(total.items(), key=lambda kv: -kv[1])),
                    "possible": dict(maybe),
                    "codes": {t: sorted(s) for t, s in st["codes"].items()},
                    "n": sum(total.values()),
                    "e": len(set().union(*st["effort"])),
                    "weeks": [
                        {
                            "w": ends[k].isoformat(),
                            "n": dict(st["det"][k]),
                            "m": dict(st["maybe"][k]),
                            "e": len(st["effort"][k]),
                        }
                        for k in range(weeks)
                        if st["effort"][k]
                    ],
                },
            }
        )
    counts |= {
        "stations": len(features),
        "organizations": len({f["properties"]["org"] for f in features}),
        "data_end": data_end.isoformat(),
    }
    return features, counts


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path("public/data/cetaceans.geojson"))
    ap.add_argument(
        "--weeks",
        type=int,
        default=13,
        help="weekly bins kept, ending at the newest analysed day",
    )
    ap.add_argument(
        "--lookback-days",
        type=int,
        default=400,
        help="rows older than this are dropped at parse time (the public record lags months)",
    )
    a = ap.parse_args(argv)
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    t0 = time.time()
    since = (
        (dt.datetime.now(dt.UTC) - dt.timedelta(days=a.lookback_days))
        .date()
        .isoformat()
    )
    orgs = fetch_organizations()
    time.sleep(SLEEP)
    themes = {}
    for theme in THEMES:
        rows, deps = fetch_theme(theme, since)
        log.info(
            "%s: %d analysed days since %s, %d deployments",
            theme,
            len(rows),
            since,
            len(deps),
        )
        themes[theme] = (rows, deps)
    features, counts = aggregate(themes, a.weeks)
    if not features:
        raise SystemExit(f"no PACM stations with analysed days since {since}")
    used = sorted({f["properties"]["org"] for f in features})
    today = dt.date.today().isoformat()
    write_atomic(
        a.out,
        {
            "type": "FeatureCollection",
            "generated_at": dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "source": {
                "id": "cetaceans",
                "name": "NOAA Passive Acoustic Cetacean Map",
                "url": APP_URL,
                "api": BASE,
                "licence": LICENCE,
                "citation": f"Passive Acoustic Cetacean Map (PACM). 2026. Woods Hole (MA): NOAA Northeast Fisheries Science Center v{PACM_VERSION}. Accessed on {today}. {APP_URL}",
                "policy": "https://www.fisheries.noaa.gov/national/about-us/website-policies-and-disclaimers",
                "note": "Counts are days with an acoustic detection at a recorder (not calls, not animals); 'possible' days are the analysts' uncertain class. Coverage follows where recorders were deployed and analysed; the public record lags months behind today.",
            },
            "data_end": counts["data_end"],
            "weeks": a.weeks,
            "since": since,
            "species": [THEMES[t] for t in THEMES],
            "themes": THEMES,
            "organizations": {o: orgs.get(o, o) for o in used},
            "counts": counts,
            "features": features,
        },
    )
    log.info("wrote %s: %s (%.0f s)", a.out, counts, time.time() - t0)


if __name__ == "__main__":
    main()
